### ISSUE TITLE
Can't push to github (files too big)

### ISSUE THREAD

**Issue by willlarche** [card-io/card.io-iOS-SDK#150] opened 2015-10-08 21:39 UTC
Since the latest version I can't push to my github repository anymore. I get these errors:

     remote: error: File Pods/CardIO/CardIO/libCardIO.a is 201.95 MB; this exceeds GitHub's file size limit of 100.00 MB

**Comment by josharian** [comment] 2015-10-08 22:06
Duplicate of #147.

**Closed by josharian** 2015-10-08 22:06 UTC
