### ISSUE TITLE
Duplicate symbols

### ISSUE THREAD

**Issue by champo** [card-io/card.io-iOS-SDK#149] opened 2015-10-07 17:31 UTC
I'm installing version `5.2.0` using cocoapods in Xcode 6.4 and I'm getting a duplicate symbols error when linking. The symbols are in CardIO files:

```
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOPaymentViewController.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOPaymentViewController.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOShutterView.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOShutterView.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIODevice.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIODevice.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIODataEntryViewController.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIODataEntryViewController.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardNumber.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardNumber.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCVVTextFieldDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCVVTextFieldDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIONumbersTextFieldDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIONumbersTextFieldDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOSectionBasedTableViewDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOSectionBasedTableViewDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIORowBasedTableViewSection.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIORowBasedTableViewSection.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOConfigurableTextFieldDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOConfigurableTextFieldDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOReadCardInfo.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOReadCardInfo.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(NSObject+CardioCategoryTest.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(NSObject+CardioCategoryTest.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOResource.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOResource.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardInfo.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardInfo.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOMultipleFieldTableViewCell.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOMultipleFieldTableViewCell.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardNumberFormatter.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardNumberFormatter.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardExpiryFormatter.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOCreditCardExpiryFormatter.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOExpiryTextFieldDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOExpiryTextFieldDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOUtilities.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOUtilities.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOMacros.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOMacros.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(dmz_all.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(dmz_all.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOAnalytics.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOAnalytics.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUFilter.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUFilter.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPURenderer.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPURenderer.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUTransformFilter.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUTransformFilter.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOBundle.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOBundle.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOContext.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOContext.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUGaussianBlurFilter.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOGPUGaussianBlurFilter.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOLocalizer.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOLocalizer.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOPostalCodeTextFieldDelegate.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOPostalCodeTextFieldDelegate.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOConfig.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOConfig.o)
duplicate symbol _llvm.cmdline in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOView.o)
duplicate symbol _llvm.embedded.module in:
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOTableViewCell.o)
    .../CardIOTest/Pods/CardIO/CardIO/libCardIO.a(CardIOView.o)
```

If I revert back to `5.1.1` it compiles without errors. 

Reproducing is simple:
1. create a new XCode project with Deployment Target set to `7.0`
1. `pod init`
1. Add `CardIO` `5.2.0` to the Podfile and `pod install`
1. Build project

**Comment by josharian** [comment] 2015-10-08 22:08
Probably a duplicate of #148, or at least the same underlying fix.

**Comment by bluk** [comment] 2015-10-19 19:19
You will need to use Xcode 7 with any Bitcode enabled library.

**Closed by bluk** 2015-10-19 19:19 UTC
Labels: question
