### ISSUE TITLE
CardIOView rotating when rotation is not desired

### ISSUE THREAD

**Issue by paultiarks** [card-io/card.io-iOS-SDK#117] opened 2015-06-03 16:00 UTC
`CardIOView` seems to be ignoring `allowFreelyRotatingCardGuide` causing the scanner to appear incorrectly rotated in some cases.  For instance when not using the scanner view full screen on iPhone and only supporting portrait orientation causes the scanner view to rotate (while the rest of the app's UI stays in portrait) when the device is rotated to landscape.

Is this a bug with the SDK or is there something I'm doing wrong?

**Comment by dgoldman-ebay** [comment] 2015-06-03 16:43
@paultiarks to prevent the CardIOView from rotating, try this:
* set `allowFreelyRotatingCardGuide` to `NO`
* set the `UISupportedInterfaceOrientation` settings in your app's plist to include only `Portrait (bottom home button)`

The latter is not strictly required, as CardIOView should respect whatever rotation constraints are imposed by the containing ViewController. But the app plist `UISupportedInterfaceOrientation` setting should override any other constraints.

**Comment by paultiarks** [comment] 2015-06-03 17:33
@dgoldman-ebay Performed both of these and the guide still rotates on device rotation for me. I could supply a test project if you're not able to reproduce on your end, or let me know any other way I could assist.

**Comment by dgoldman-ebay** [comment] 2015-06-04 17:40
@paultiarks I am able to reproduce this problem. So far it's not apparent to me why this is no longer working. I will have to dig deeper...

Thanks for bringing this issue to our attention!

**Comment by dgoldman-ebay** [comment] 2015-06-08 06:16
@paultiarks This is rather interesting. I'm reasonably sure that a year or two ago I extensively tested this part of the code, and all was well. But I agree with you that it's not working now.

When `allowFreelyRotatingCardGuide` is set to `NO`, the card.io code follows the `UIResponder` chain upward from the `CardIOView` to find the first `UIViewController`. It then calls that viewcontroller's `supportedInterfaceOrientations` method, and the result determines the allowable orientations for the card guide.

So please take a close look at your view controller's `supportedInterfaceOrientations` method. Presumably it's not returning what you'd expect.

In the case of card.io's `CardIOPaymentViewController`, all of my tests today indicate that iOS is failing to do what it promises to do in the default `[UIViewController supportedInterfaceOrientations]` method;  namely, intersecting the results with the `UISupportedInterfaceOrientations` value from the app's plist. I will probably update our code to do this intersection on its own.

(You can probably simply fix this in your view controller's `supportedInterfaceOrientations` method itself, rather than worrying about the plist.)

**Comment by paultiarks** [comment] 2015-06-09 19:33
@dgoldman-ebay This fixes the issue enough that I think we can consider it closed.  If this is fixed in your code such that we don't have to override `supportedInterfaceOrientation` then an update on this thread would be appreciated, if at all possible, so we can pull that new version in.  Thank you for your time and assistance!

**Comment by tomwhipple** [comment] 2015-06-30 16:07
Since @dgoldman-ebay has moved on to other things, I'm going to close this. Should someone decide to submit a pull request, we will review it. ;)

**Closed by tomwhipple** 2015-06-30 16:07 UTC
Labels: bug

**Comment by dgoldman-ebay** [comment] 2015-07-13 00:03
Fixed in [Version 5.1.0](https://github.com/card-io/card.io-iOS-SDK/releases).
