### ISSUE TITLE
CardHolder name

### ISSUE THREAD

**Issue by Dellybro** [card-io/card.io-iOS-SDK#287] opened 2018-06-14 23:22 UTC
Maybe a good implementation would be to add "cardHolder name" to the cameras functionality. Having my user have to type in their cardholder name when it's already in the view of the camera is kind of tedious

**Comment by Jlugosan** [comment] 2018-06-22 23:05
any solution ?

**Comment by josharian** [comment] 2018-06-23 04:25
Duplicate of #111

**Closed as completed by josharian** 2018-06-23 04:25 UTC
